"""Add must_change_password flag

Revision ID: 039eb8c11ab2
Revises: 5fafb928dc51
Create Date: 2026-09-24 00:51:51.041841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '039eb8c11ab2'
down_revision: Union[str, Sequence[str], None] = '5fafb928dc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'must_change_password')
    # ### end Alembic commands ###
