"""Add fields to CorrectionRequest

Revision ID: 5fafb928dc51
Revises: 386efba06a5d
Create Date: 2026-09-24 00:06:55.798273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5fafb928dc51'
down_revision: Union[str, Sequence[str], None] = '386efba06a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correctionrequest', sa.Column('record_id', sa.Integer(), nullable=False))
    op.add_column('correctionrequest', sa.Column('proposed_status', sa.Enum('PRESENT', 'ABSENT', name='attendancestatus'), nullable=False))
    op.add_column('correctionrequest', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'correctionrequest', 'attendancerecord', ['record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'correctionrequest', type_='foreignkey')
    op.drop_column('correctionrequest', 'rejection_reason')
    op.drop_column('correctionrequest', 'proposed_status')
    op.drop_column('correctionrequest', 'record_id')
    # ### end Alembic commands ###
